image: gitpod/workspace-full-vnc

tasks:
- name: SETUP
  init: |
    # install fuse as a pre-requisite for AppImage
    sudo apt -y install libfuse2 fuse
    
    # Download BandageNG
    cd /workspace
    wget https://github.com/asl/BandageNG/releases/download/continuous/BandageNG-Linux-8dd0544.AppImage
    mv BandageNG-Linux-8dd0544.AppImage BandageNG
    chmod u+x BandageNG
  command: |
    ls -lA /workspace && /workspace/BandageNG
    
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

workspaceLocation: "/workspace"
